### ISSUE TITLE
Session Timeout and Unsaved code (TI vs Rule)

### ISSUE THREAD

**Issue by grandryjn** [cubewise-code/arc-issues#155]
In some case, I am disconnected from TM1 through ARC (most likely timeout).
I don't notice it until I try to save an object or when I refresh the object list.

In general when I click save, a prompt windows asking the credential is displayed and then a message suggest to run the last action:
- When I work on a TI, that's fine, the unsaved code is still there and I can save it "again".
- When I work on a Rule, it seems it is refreshing the rule file back to how it was and therefore the unsaved code is lost.

Is there a way to have the same behaviour on the Rule?
Otherwise a notification informing that the session is no longer connected to TM1.

**Comment by psegal** [comment]
+1 on this. It's caught me out a couple of times now.

**Comment by lotsaram** [comment]
+1 for me also. It is actually a great "feature" when editing a TI that if the session times out, or the instance is restarted, or the session token is lost for any other reason, that Arc will give you a message that "the action needs to be repeated due to session timeout" and then just log you back in in the background and perform the update seamlessly on the next mouse-click without losing any work. The same should apply for rules as well.

**Comment by cubewise-tryan** [comment]
Hi @grandryjn,

I can't repeat this issue, when my session times out the unsaved changes are still in the browser. What version are you using?

**Comment by lotsaram** [comment]
I just checked in 0.9.8 and it is fixed there. Rules now behave same as TI.

**Comment by cubewise-tryan** [comment]
@lotsaram, thanks for the update.
