### ISSUE TITLE
SQL Query Preview

### ISSUE THREAD

**Issue by kmurphy111** [cubewise-code/arc-issues#171]
ARC 0.9.7
TM1 Planning Analytics 11.3.00000.27
Browser: Chrome Version 67.0.3396.99

Not sure if this is user error or an issue. We use the TM1 service account as our AD account to run SQL queries. So there are no SQL user credentials in TI processes. I don't seem to be able to preview these queries in arc although they run fine when executing the process in arc. I am using arc installed on the TM1 server. Below is the error i get. Is there some config i need to do to get SQL query preview to work. Thanks.

![sql preview](https://user-images.githubusercontent.com/41028072/43301239-46cdb6ee-91a7-11e8-9ca4-fde5b546786e.JPG)

**Comment by cubewise-tryan** [comment]
Hi @kmurphy111,

Arc at the moment is executing the SQL queries itself rather than through TM1. This means that you will need to run Arc under the service account so the credentials are passed through. 

In TM1 11.3/2.0.5 there are new actions to execute a query through TM1. We will add support for these.

**Comment by kmurphy111** [comment]
I tried running SQL previews logged into arc as the service account but still does not work. I also have access to the tables and does not work logged into arc as me. One thing i did not mention is that we use CAM security.
