### ISSUE TITLE
Save hotkey issue

### ISSUE THREAD

**Issue by jgorsk** [cubewise-code/arc-issues#176]
In Polish keyboard setting combination Alt+s is used for for special Polish sign 'ś'. I cannot make that sign in Arc as it is saving object I'am editing. Can this shortcut be configurable like Ctrl+Space?

**Comment by cubewise-tryan** [comment]
Hi @jgorsk,

Arc uses Ctrl+s for saving not Alt+s. It is possible to create an interface for the key mappings but it isn't a high priority at the moment.

**Comment by jgorsk** [comment]
@cubewise-tryan 
Both combinations works for me, Ctrl+s and Alt+s (To be exact - it is right Alt. Left Alt + s do not save the rule). I tried to change keyboard settings and alt+s still saves the rule.

**Comment by cubewise-tryan** [comment]
Hi @jgorsk,

Alt (left or right) doesn't do anything on my keyboard (US layout). Do you have the same issue in other applications?

**Comment by jgorsk** [comment]
Hey @cubewise-tryan 

I tried office suite, np++ and google search with the browser (IE) i'm using arc - all give me proper ś sign - only arc is performing save.

**Comment by PiotrRajtar** [comment]
Hi @jgorsk & @cubewise-tryan,

That is an interesting one, I tested it as well and it seems that the issue is specific only to Polish keyboard layout when using Arc in IE. Chrome works fine.

When using the Polish layout, Right Alt+S should be normally interpreted as AltGr+S (Alt Graph) or at least as Ctrl+Alt+S when AltGr is not supported and just print "ś". This it how it works in Chrome. It seems that for some reason in IE it is interpreted by Arc as just Ctrl+S and triggers a save.

The issue seems to be specific to Arc as pure Ace Editor does not have it.

**Comment by cubewise-tryan** [comment]
Hi @PiotrRajtar,

Thanks for the info, we only check for Ctrl+s but don't check if other keys are held. I assume if we make sure Alt isn't also press it will solve the issue.

**Comment by PiotrRajtar** [comment]
Hi @cubewise-tryan,

I would think so, but it is still interesting that Chrome handles it correctly at the moment even if you don't specifically check for Alt.
