### ISSUE TITLE
Sessions in Arc vs. TM1 Top (question)

### ISSUE THREAD

**Issue by hermie64** [cubewise-code/arc-issues#306]
Can you please explain the relationship between the ID's displayed in Arc versus TM1 Top (see screenshot)?

We're using security mode 5 and in Arc Sessions I see both my domain/user (Te) and CAMID.
In TM1 Top I see multiple ID's for what seems one ID in Arc Sessions.

![2018-11-16_101620](https://user-images.githubusercontent.com/5301621/48756832-f5566a00-ec9a-11e8-816e-142dcfc0698f.png)

**Comment by rclapp** [comment]
Keep in mind that tm1top does not entirely comply with the new REST standards.

**Sessions:** tied to an authentication event, like logging into arc. Non-expired Sessions are reusable and portable (arc to tm1web for instance). Sessions are identified by a session ID stored as a cookie. 

**Threads:** perform tasks and serve as workers. Threads are generated automatically as needed. 1 session can have many threads. You can see this by running 2 processes from arc at once. 

Tm1 top has added the session identifier to the context column, but it is actually a unique thing. For cases where arc is not showing the default display name, check you have the alias properly set.

**Comment by cubewise-tryan** [comment]
Hi @hermie64,

@rclapp has given most of the details, the key distinction is that there are 2 types of sessions mechanisms in TM1:

**Old C API**
This is the used for any interface that uses the C API, main ones being Architect and Perspectives. When using this API each user is assigned a single thread that they use solely for the entire time they are logged into TM1. ThreadID = User. They can also be worker threads for multi-threaded queries.

In programming terms threads are a finite resource on the OS and require certain system resources. If you want to have 1000's of users you are generally better off to share them for short-lived operations rather than 1 per user.

**REST API**
The REST API as @rclapp says uses a session for each user and then shares the threads between the sessions. SessionID = User. This means it should be able to handle more concurrent users than the old model. Sessions can have no threads assigned to them is they are idle for a certain amount of time.

Arc combines sessions and threads to give a full picture of who is logged in to TM1 irrespective of the API. The new Pulse that will work on the REST API will do the same.

**Comment by hermie64** [comment]
Thank you both!

@rclapp: Regarding: "_For cases where arc is not showing the default display name, check you have the alias properly set._"
Attribute }TM1_DefaultDisplayValue is set for }Clients dim, so I don't know why we're seeing CAMID instead?
